"""Independent conversion project (spec section 6, "独立目录支持").

When the resource directory has no neighbouring ``.uproject`` we generate a
throwaway Unreal project whose ``Content`` folder *is* the user's directory.
Unreal then mounts it at ``/Game``, which preserves Content-relative asset
paths exactly as the spec requires.

The source directory is never written to. ``junction`` mode (the default)
exposes it through an NTFS directory junction, which costs no disk space and
no copy time; ``copy`` mode is available when the source must be snapshotted.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from ..errors import ConfigError
from ..logutil import get_logger
from ..unreal.paths import MOUNT_GAME

_log = get_logger("unreal.project")

MARKER_NAME = ".fbxconv-project.json"
DEFAULT_PROJECT_NAME = "FbxConvProject"
PROGRESS = Callable[[str], None]


class MountMode(str, Enum):
    JUNCTION = "junction"
    COPY = "copy"
    HARDLINK = "hardlink"

    @property
    def label(self) -> str:
        return {
            MountMode.JUNCTION: "目录联接（零拷贝）",
            MountMode.COPY: "完整复制",
            MountMode.HARDLINK: "硬链接",
        }[self]


@dataclass
class ConversionProject:
    """A generated Unreal project that mounts an external content directory."""

    root: Path
    content_source: Path
    engine_version: str = ""
    mount_mode: MountMode = MountMode.JUNCTION
    name: str = DEFAULT_PROJECT_NAME
    _created_mode: str = field(default="", init=False)

    # ------------------------------------------------------------------ paths

    @property
    def uproject(self) -> Path:
        return self.root / f"{self.name}.uproject"

    @property
    def content_dir(self) -> Path:
        return self.root / "Content"

    @property
    def marker(self) -> Path:
        return self.root / MARKER_NAME

    @property
    def mount_point(self) -> str:
        return MOUNT_GAME

    # -------------------------------------------------------------- lifecycle

    def is_up_to_date(self) -> bool:
        """True when an on-disk project already matches this configuration."""
        if not self.uproject.is_file() or not self.content_dir.exists():
            return False
        try:
            payload = json.loads(self.marker.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return False
        return (
            payload.get("content_source") == str(self.content_source)
            and payload.get("engine_version") == self.engine_version
            and payload.get("mount_mode") == self.mount_mode.value
        )

    def create(self, *, reuse: bool = True, progress: PROGRESS | None = None) -> Path:
        """Materialise the project; returns the ``.uproject`` path."""
        if reuse and self.is_up_to_date():
            self._created_mode = self.mount_mode.value
            _log.info("复用现有转换项目：%s", self.root)
            return self.uproject

        self.root.mkdir(parents=True, exist_ok=True)
        self._remove_content_mount()
        self._write_uproject()
        self._create_content_mount(progress=progress)
        self._write_marker()
        _log.info("已创建转换项目 %s（挂载模式 %s）", self.root, self.mount_mode.value)
        return self.uproject

    def cleanup(self) -> None:
        """Remove the generated project (never touches the source directory)."""
        if not self.root.exists():
            return
        shutil.rmtree(self.root, ignore_errors=True)
        _log.info("已删除转换项目：%s", self.root)

    # ---------------------------------------------------------------- internal

    def _remove_content_mount(self) -> None:
        content = self.content_dir
        if not content.exists():
            return
        # A junction is removed with rmdir; a real directory needs rmtree.
        if _is_reparse_point(content):
            try:
                os.rmdir(content)
                return
            except OSError:  # pragma: no cover - fall back to full removal
                pass
        shutil.rmtree(content, ignore_errors=True)

    @property
    def engine_association(self) -> str:
        """Unreal expects a ``Major.Minor`` association, not a full version."""
        parts = [p for p in (self.engine_version or "").split(".") if p]
        if len(parts) >= 2:
            return ".".join(parts[:2])
        return self.engine_version or ""

    def _write_uproject(self) -> None:
        payload = {
            "FileVersion": 3,
            "EngineAssociation": self.engine_association,
            "Category": "",
            "Description": "Generated by FbxConverter - do not edit by hand.",
            "Plugins": [
                {"Name": "PythonScriptPlugin", "Enabled": True},
                {"Name": "EditorScriptingUtilities", "Enabled": True},
            ],
        }
        self.uproject.write_text(
            json.dumps(payload, indent=2) + "\n", encoding="utf-8"
        )

    def _create_content_mount(self, *, progress: PROGRESS | None = None) -> None:
        source = self.content_source
        if not source.is_dir():
            raise ConfigError(f"资源目录不存在：{source}")

        if self.mount_mode is MountMode.JUNCTION and os.name == "nt":
            if _make_junction(self.content_dir, source):
                self._created_mode = MountMode.JUNCTION.value
                return
            _log.warning("目录联接创建失败，回退为完整复制")
            if progress:
                progress("目录联接不可用，正在复制资源…")

        if self.mount_mode is MountMode.HARDLINK:
            if _make_hardlink_tree(source, self.content_dir, progress=progress):
                self._created_mode = MountMode.HARDLINK.value
                return
            _log.warning("硬链接创建失败（可能跨卷），回退为完整复制")

        if progress:
            progress("正在复制资源到转换项目…")
        shutil.copytree(source, self.content_dir, symlinks=True, dirs_exist_ok=True)
        self._created_mode = MountMode.COPY.value

    def _write_marker(self) -> None:
        self.marker.write_text(
            json.dumps(
                {
                    "content_source": str(self.content_source),
                    "engine_version": self.engine_version,
                    "mount_mode": self.mount_mode.value,
                    "created_mode": self._created_mode,
                    "created_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
                },
                indent=2,
            ),
            encoding="utf-8",
        )

    def to_payload(self) -> dict[str, str]:
        return {
            "root": str(self.root),
            "uproject": str(self.uproject),
            "content_source": str(self.content_source),
            "mount_mode": self._created_mode or self.mount_mode.value,
            "mount_point": self.mount_point,
        }


def _is_reparse_point(path: Path) -> bool:
    try:
        return bool(os.lstat(path).st_file_attributes & 0x400)  # FILE_ATTRIBUTE_REPARSE_POINT
    except (OSError, AttributeError):  # pragma: no cover - non-Windows
        return False


def _make_junction(link: Path, target: Path) -> bool:
    """Create an NTFS directory junction. Needs no elevation."""
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.exists():
        return False
    try:
        completed = subprocess.run(
            ["cmd", "/c", "mklink", "/J", str(link), str(target)],
            capture_output=True,
            text=True,
            check=False,
            shell=False,
        )
    except OSError as exc:  # pragma: no cover
        _log.warning("mklink 调用失败：%s", exc)
        return False
    if completed.returncode != 0:
        _log.warning("mklink 失败：%s", (completed.stderr or completed.stdout or "").strip())
        return False
    if not link.is_dir():
        return False
    try:
        # Prove the junction actually resolves to the source.
        next(os.scandir(link), None)
    except OSError:  # pragma: no cover
        return False
    return True


def _make_hardlink_tree(
    source: Path, destination: Path, *, progress: PROGRESS | None = None
) -> bool:
    """Mirror ``source`` into ``destination`` using hard links."""
    try:
        destination.mkdir(parents=True, exist_ok=True)
        total = 0
        for dirpath, _dirnames, filenames in os.walk(source):
            rel = Path(dirpath).relative_to(source)
            target_dir = destination / rel
            target_dir.mkdir(parents=True, exist_ok=True)
            for name in filenames:
                src_file = Path(dirpath) / name
                dst_file = target_dir / name
                if dst_file.exists():
                    continue
                try:
                    os.link(src_file, dst_file)
                except OSError:
                    shutil.copy2(src_file, dst_file)
                total += 1
                if progress and total % 500 == 0:
                    progress(f"已链接 {total} 个文件…")
        return True
    except OSError as exc:
        _log.warning("硬链接镜像失败：%s", exc)
        return False


def ensure_conversion_project(
    work_root: Path,
    content_source: Path,
    *,
    engine_version: str = "",
    mount_mode: MountMode | str = MountMode.JUNCTION,
    name: str = DEFAULT_PROJECT_NAME,
    reuse: bool = True,
    progress: PROGRESS | None = None,
) -> ConversionProject:
    """Create (or reuse) the independent conversion project."""
    if isinstance(mount_mode, str):
        try:
            mount_mode = MountMode(mount_mode)
        except ValueError:
            mount_mode = MountMode.JUNCTION
    project = ConversionProject(
        root=Path(work_root) / "UnrealProject",
        content_source=Path(content_source).resolve(),
        engine_version=engine_version,
        mount_mode=mount_mode,
        name=name,
    )
    project.create(reuse=reuse, progress=progress)
    return project


__all__ = [
    "DEFAULT_PROJECT_NAME",
    "MARKER_NAME",
    "ConversionProject",
    "MountMode",
    "ensure_conversion_project",
]
